// Code generated by github.com/skipor/gmg - type-safe, fast and handy alternative GoMock generator. DO NOT EDIT.
// Source: library/api/service/actions.Connector

package mocks_actions

import (
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// NewMockConnector creates a new GoMock for library/api/service/actions.Connector.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	return &MockConnector{ctrl: ctrl}
}

// MockConnector is a GoMock of library/api/service/actions.Connector.
type MockConnector struct{ ctrl *gomock.Controller }

// EXPECT returns GoMock recorder.
func (m_ *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return (*MockConnectorMockRecorder)(m_)
}

// GetConnection implements mocked interface.
func (m_ *MockConnector) GetConnection() (*sql.DB, error) {
	m_.ctrl.T.Helper()
	res_ := m_.ctrl.Call(m_, "GetConnection")
	res0, _ := res_[0].(*sql.DB)
	res1, _ := res_[1].(error)
	return res0, res1
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder MockConnector

// GetConnection() (*sql.DB, error)
func (r_ *MockConnectorMockRecorder) GetConnection() MockConnectorGetConnectionCall {
	r_.ctrl.T.Helper()
	call := r_.ctrl.RecordCallWithMethodType(r_.mock(), "GetConnection", reflect.TypeOf((*MockConnector)(nil).GetConnection))
	return MockConnectorGetConnectionCall{call}
}

// MockConnectorGetConnectionCall is type safe wrapper of *gomock.Call.
type MockConnectorGetConnectionCall struct{ *gomock.Call }

// DoAndReturn is type safe wrapper of *gomock.Call DoAndReturn.
func (c_ MockConnectorGetConnectionCall) DoAndReturn(f func() (*sql.DB, error)) MockConnectorGetConnectionCall {
	c_.Call.DoAndReturn(f)
	return c_
}

// Do is type safe wrapper of *gomock.Call Do.
func (c_ MockConnectorGetConnectionCall) Do(f func()) MockConnectorGetConnectionCall {
	c_.Call.Do(f)
	return c_
}

// Return is type safe wrapper of *gomock.Call Return.
func (c_ MockConnectorGetConnectionCall) Return(res0 *sql.DB, res1 error) MockConnectorGetConnectionCall {
	c_.Call.Return(res0, res1)
	return c_
}

func (r_ *MockConnectorMockRecorder) mock() *MockConnector {
	return (*MockConnector)(r_)
}
