# Используем официальный MySQL образ.
FROM mysql:5.7

# Устанавливаем переменные окружения
#todo: добавить динамическую подстановку параметром
ENV MYSQL_ROOT_PASSWORD=sho
ENV MYSQL_DATABASE=local
ENV MYSQL_USER=local
ENV MYSQL_PASSWORD=local

# Миграция бд
COPY ./cmd/docker/sql-scripts.sql /docker-entrypoint-initdb.d/